"""empty message

Revision ID: ed961544cf23
Revises: 
Create Date: 2022-11-15 11:23:27.495648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed961544cf23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=124), nullable=False),
    sa.Column('password_hash', sa.String(length=511), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('car_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_opportunity', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', postgresql.ENUM('yellow', 'blue', 'gray', name='Color'), nullable=False),
    sa.Column('model', postgresql.ENUM('hatch', 'sedan', 'convertible', name='Model'), nullable=False),
    sa.Column('car_owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_owner_id'], ['car_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('car_owners')
    op.drop_table('auths')
    # ### end Alembic commands ###
